### ISSUE TITLE
isuue in the config file

### ISSUE THREAD

**Issue by hayyanHasan** [pilgun/acvtool#10]
Hello....
thank you for your code ... I tried to use it in Ubuntu 16.04.6 LTS (Xenial Xerus).... I install all the requirements mentioned in the read-me file .. when an I installed it without any error 
  when I tried the **acv -h** instruction the following error came up:

**File "/home/hayyan/Desktop/acvtool/acvtool.py", line 8, in <module>
    from smiler import smiler
  File "/home/hayyan/Desktop/acvtool/smiler/smiler.py", line 10, in <module>
   from config import config
ImportError: No module named 'config'**

Any ideas??
Best regards...

**Comment by pilgun** [comment]
Hi, @hayyanHasan 
Have you created config.json as it mentioned in readme.md?

**Comment by hayyanHasan** [comment]
Hello @pilgun.. thank you for your response....
actually yes... But also it did not work so I tried to change the code in the smiler.py file to be like the following:
 **from smiler.config import config
from smiler.granularity import Granularity** 
and it works for me, but Now I am facing another error which is: "**the code does not recognize the paths in the config.json file"** like the following 
**ERROR:root:apksigner was not found at HOME/Android/sdk/build-tools/29.0.2/apksigner
ERROR:root:adb tool was not found at HOME/Android/sdk/platform-tools/adb
ERROR:root:aapt tool was not found at HOME/Android/sdk/build-tools/29.0.2/aapt
ERROR:root:zipalign was not found at HOME/Android/sdk/build-tools/29.0.2/zipalign
ERROR:root:
CONFIGURATION ERROR: Please check paths at /home/hayyan/acvtool/config.json or/and install required software.**
Best regards...

**Comment by pilgun** [comment]
You need to specify full and correct paths in config.json. They are just
examples there.

**Comment by hayyanHasan** [comment]
Hi @pilgun ..... I would thank you very much for your response.... 
the Problem was in the pip.... I did not be attention to the version of Python
Best Regards...
