### ISSUE TITLE
Coverage on instrumented app crash

### ISSUE THREAD

**Issue by migueltouret** [pilgun/acvtool#12]
Hi, is there any way (or will there any way in the future) for acvtool to obtain code coverage for an app even when the app crashes?

**Comment by pilgun** [comment]
Hi Miguel, this functionality is implemented.
Some details are here https://github.com/pilgun/acvtool/issues/8#issuecomment-495898872
I remember there was a known problem in Android when handling exception by Instrumentation class. As of now it's not in my head, but I consider to come back to it later.

**Comment by migueltouret** [comment]
In the comment its said that crashes are logged into a errors.txt file but i cant seem to find it, where is the file created?
This is acv's output in the command line
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

**Comment by pilgun** [comment]
Acvtool is about coverages rather then crashes. Catching them through
Instrumentation process isn’t reliable. I.e., if instrumentation process
crashes itself, it will be impossible to catch anything. Yet, it’s
implemented to give as much info as possible. Always use logcat to reveal
crashes reliably.
