### ISSUE TITLE
Error when path to APK contains space

### ISSUE THREAD

**Issue by SoulXHades** [pilgun/acvtool#21]
![image](https://user-images.githubusercontent.com/18703340/103896251-a8f56f00-512c-11eb-9bdf-555b8fc1b9df.png)

**Comment by pilgun** [comment]
Hi @SoulXHades 

space character in your path might be an issue at this step

**Comment by SoulXHades** [comment]
![image](https://user-images.githubusercontent.com/18703340/103898574-15be3880-5130-11eb-800c-823580e31121.png)

**Comment by pilgun** [comment]
Could you repackage this apk using just apktool (decompile and assemble again) first?
