### ISSUE TITLE
Permission denied on going to /mnt/sdcard/*

### ISSUE THREAD

**Issue by AlienX2001** [pilgun/acvtool#30]
Hey,
I was just trying to use acvtool with my non-rooted moto g40 fusion running android12.
I was just testing this tool on a simply 2048 game.

I can instrument the apk just fine and install it. But when I try to run it using `acv start <package.name>` it doesnt start the apk. In the terminal it says `Press Ctrl+C to finish ...` but I have to start the app manually.

After opening the app manually and interacting with it for a while I press Ctrl+C and get the following error
```Exception Exception: Exception('----------------------------------------------------\nOut: \nError: ls: /mnt/sdcard/com.tpcstld.twozerogame/: Permission denied\n',) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored```

This is the apk link https://m.apkpure.com/2048/com.tpcstld.twozerogame/download

Screenshots for your reference:-

![Screenshot from 2023-03-28 15-42-39](https://user-images.githubusercontent.com/64488123/228204457-d0f7f696-ab01-4b8b-ae86-299eb7473115.png)

From the looks of it, it should work if phone or atleast adb is rooted.
So just to confirm will this tool require root, or can it work without root as well?

**Comment by pilgun** [comment]
Hi AlienX2001,

Apparently Android has slightly changed its storage structure and permissions. Still, no need for root.

Please checkout new changes and run everything from scratch.

Thank you for reporting this issue.

**Comment by AlienX2001** [comment]
Could you confirm which resources are the code looking for?  Is it looking for libraries, oat, base.apk, etc. as in the first screenshot. Or the user data like that in second screenshot? I will make the necessary changes accordingly

**Comment by pilgun** [comment]
ACVTool needs a place on your phone to store coverage information. It used
to create a folder /mnt/sdcard/<package> to save coverage (*.ec) files. But
in the new Android "/mnt" is not accessible anymore. Now we store files at
the /sdcard/Download/<package> folder.

ACVTool doesn't look for other resources on your phone.

Please feel free do git pull or see changes in the last commit.

**Comment by AlienX2001** [comment]
Thanks, the code works now as intended
