### ISSUE TITLE
acv start process crashed

### ISSUE THREAD

**Issue by InterestingApple** [pilgun/acvtool#31]
I have the following problem when I combine the acvtool with automated testing tools. I first use the command "acv start com.ichi2.anki" to start the instrument process,then I testing the application with automated testing tools,and then when it run to the fifth minute,there is a crash below and the "acv start ..." process is terminated and stops running. So the .ec file not be generated after the process crash. Can you help me?

Problem:
jie@jie-Legion-Y9000P-IAH7H:~/acvtool/acvtool_working_dir$ acv start com.ichi2.anki
Press Ctrl+C to finish ...
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

jie@jie-Legion-Y9000P-IAH7H:~/acvtool/acvtool_working_dir$

**Comment by jdanceze** [comment]
I have the same problem running the instrumented apk with appium. Did you manage to find any solution?
