### ISSUE TITLE
How to integrate with Sapienz?

### ISSUE THREAD

**Issue by jdanceze** [pilgun/acvtool#32]
I have a sample set of APKs that work fine on Sapienz for Android Emulator 4.4 (as it is stated that Sapienz supports Android 4.4). However, when I try them on newer versions of Android such as Android 5, 7, 8, 10, and 11, Sapienz does not seem to generate any activity for testing. I wonder how I can run the instrumented APKs on newer versions of Android then running the test from Sapienz.

**Comment by pilgun** [comment]
Sorry for ignoring your question. Please let me know if you still need an advice on your issue.
