### ISSUE TITLE
how to timeout after a certain amount of time.

### ISSUE THREAD

**Issue by goku1142** [pilgun/acvtool#35]
I want to get the report of the application using acv tool after running(using the acv start command) it for 10 seconds. Could you please explain a bit about what changes would be required to be made to automatically timeout the application after 10 seconds instead of keyboard interrupt.

**Comment by pilgun** [comment]
You could use the flag `-w` to run the process in the background and the call `stop` when you would like to finish it
`acv start -w <package_name>`
`acv stop <package_name>`

**Comment by goku1142** [comment]
on running the command acv start -w <package_name> it shows -w is an unrecognised argument

**Comment by pilgun** [comment]
Sorry, it's `-q` instead of `-w`. Also you can find a few explanations in the help menu `acv start -h`
