### ISSUE TITLE
Crash or failed instrumentation

### ISSUE THREAD

**Issue by up201907932** [pilgun/acvtool#40]
Hi, I have successfully instrumented this app https://f-droid.org/en/packages/me.lucky.silence/. The install gives an exception because it tries a incremental install but then tries a streamed install that succeeds. When I try to start the app it immediately crashes.
![image](https://github.com/pilgun/acvtool/assets/92312536/e7bbd339-b57c-4885-ac1c-e171f897990e)
When I try to instrument https://f-droid.org/en/packages/com.kylecorry.trail_sense/, I get:
![image](https://github.com/pilgun/acvtool/assets/92312536/b75e9470-deec-49a8-b063-9ece53ca6eb5)
I have updated apktool to the most recent version, as suggested in another issue, but I still get "Unable to open <file> as zip archive."
Any ideas?

**Comment by pilgun** [comment]
Hey Nuno,

Thanks for trying ACVTool! Unfortunately, I have to leave these issues not
solved. Hopefully, everything works with a new release of ACVTool (coming
soon)
