### ISSUE TITLE
Can I change the package name of the new package after modifying the acv instrument

### ISSUE THREAD

**Issue by RayPengzhihui** [pilgun/acvtool#44]
Due to various reasons, this apk cannot be uninstalled on the phone. I think the package printed after ACV Instrument has a different package name than the original package. This way, two Android applications with the same package but different package names can be installed on the upper level.
Is there a way to modify the package name when using ACV Instrument?

**Comment by RayPengzhihui** [comment]
Hey @pilgun 
Because the packages that need to be uninstalled and reinstalled are pre installed applications, only rooted phones can uninstall them

**Comment by pilgun** [comment]
Good point. Do you think this kind of apps can be re-installed and run on
other devices with clean Android?
