### ISSUE TITLE
No module named "config" error

### ISSUE THREAD

**Issue by omeerkorkmazz** [pilgun/acvtool#5]
Hello,

I completed all sections. When I run "acv -h" command, it says that no mdule named "config" in smiler.py. I think that there is problem with naming in the python files because I modified import section smiler.config instead of config. However, it starts to give error another naming related folders. I changed many parts but still it is not working. Do you have any idea about the problem? 

Note: I use python 3.6.0. Does it make a problem?

**Comment by pilgun** [comment]
Hi Omer,

Please use Python 2.6+. ACVTool does not work with Python 3 yet.
